//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int ItemID { get; set; }

        [Required(ErrorMessage ="The Item Name is required")]
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        [Required(ErrorMessage = "The Item Supplier is required")]
        public string ItemSupplier { get; set; }
        [Required(ErrorMessage = "The Item Brand is required")]
        public string ItemBrand { get; set; }
        [Required(ErrorMessage = "The Item Category is required")]
        public string ItemCategory { get; set; }
        [Required(ErrorMessage = "The Item Price is required")]
        [Range(1.0, double.MaxValue, ErrorMessage = "Should be Greater of Equal than 1")]
        public double ItemPrice { get; set; }
        [Required(ErrorMessage = "The Item Stock is required")]
        public int ItemStock { get; set; }
    }
}
